name: ESP32 Builder

on: [push]

jobs:
  builder:
    name: Builder for ESP32 project
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ESP-IDF
        uses: CalinRadoni/esp-idf-v4-action@v2
        with:
          esp_idf_version: 'v4.4'

      - name: Build
        run: |
          source ~/esp/esp-idf/export.sh
          cd hello_world
          idf.py build
